# _config.yml
theme: jekyll-theme-primer
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript

# Add other necessary configs
title: PT Face Visualize
description: Your project description here